import type { Question } from "../types";

export const DEFAULT_QUESTIONS: Question[] = [
  // --- Matematika va Mantiq ---
  {
    id: "1",
    subject: "Matematika",
    question: "Agar uchburchakning katetlari 6 sm va 8 sm bo'lsa, uning gipotenuzasi nechiga teng?",
    options: ["10 sm", "12 sm", "14 sm", "16 sm"],
    correctAnswer: "10 sm",
    difficulty: "hard",
    timeLimit: 40,
  },
  {
    id: "2",
    subject: "Matematika",
    question: "Log2(32) + 3^2 ifodaning qiymati nechiga teng?",
    options: ["13", "14", "15", "16"],
    correctAnswer: "14",
    difficulty: "hard",
    timeLimit: 45,
  },
  {
    id: "3",
    subject: "Matematika",
    question: "Idishdagi suvning hajmi har kuni ikki barobar ortib bormoqda. Agar idish 30 kunda to'lsa, u necha kunda yarmigacha to'lgan bo'ladi?",
    options: ["15 kunda", "29 kunda", "14 kunda", "25 kunda"],
    correctAnswer: "29 kunda",
    difficulty: "hard",
    timeLimit: 40,
  },
  {
    id: "4",
    subject: "Matematika",
    question: "Funksiyaning hosilasi y = x^3 bo'lsa, uning boshlang'ich funksiyasi qanday?",
    options: ["(x^4) / 4", "3x^2", "x^2 / 2", "4x^4"],
    correctAnswer: "(x^4) / 4",
    difficulty: "hard",
    timeLimit: 45,
  },

  // --- Fizika va Kimyo ---
  {
    id: "5",
    subject: "Fizika",
    question: "Vakuumda yorug'lik tezligi (c) taxminan qanday qiymatga ega?",
    options: ["300 000 km/s", "150 000 km/s", "3 000 km/s", "30 000 km/s"],
    correctAnswer: "300 000 km/s",
    difficulty: "medium",
    timeLimit: 35,
  },
  {
    id: "6",
    subject: "Fizika",
    question: "Nyutonning ikkinchi qonuni qaysi formulada ifodalanadi?",
    options: ["F = m * a", "E = m * c^2", "P = m * g", "F = G * (m1*m2)/r^2"],
    correctAnswer: "F = m * a",
    difficulty: "medium",
    timeLimit: 35,
  },
  {
    id: "7",
    subject: "Kimyo",
    question: "Diyagrammada pH qiymati 2 ga teng bo'lgan eritma qanday muhitga ega?",
    options: ["Kuchli kislotali", "Kuchli ishqoriy", "Neytral", "Kuchsiz ishqoriy"],
    correctAnswer: "Kuchli kislotali",
    difficulty: "hard",
    timeLimit: 40,
  },
  {
    id: "8",
    subject: "Kimyo",
    question: "Mendeleyev jadvalidagi qaysi element 'Oltin' deb ataladi va uning belgisi qanday?",
    options: ["Ag (Kumush)", "Au (Oltin)", "Cu (Mis)", "Fe (Temir)"],
    correctAnswer: "Au (Oltin)",
    difficulty: "medium",
    timeLimit: 30,
  },

  // --- Jahon va O'zbekiston tarixi ---
  {
    id: "9",
    subject: "Tarix",
    question: "Amir Temur asos solgan imperiyaning poytaxti qaysi shahar edi?",
    options: ["Buxoro", "Samarqand", "Xiva", "Toshkent"],
    correctAnswer: "Samarqand",
    difficulty: "medium",
    timeLimit: 35,
  },
  {
    id: "10",
    subject: "Tarix",
    question: "Buyuk ipak yo'li qaysi qit'alarni asosiy bog'lab turgan?",
    options: ["Yevropa va Osiyo", "Amerika va Afrika", "Avstraliya va Yevropa", "Afrika va Osiyo"],
    correctAnswer: "Yevropa va Osiyo",
    difficulty: "medium",
    timeLimit: 35,
  },
  {
    id: "11",
    subject: "Tarix",
    question: "Antik davrda 'Movarounnahr' atamasi geografik jihatdan nimani anglatgan?",
    options: ["Tog'lar orasidagi vodiyni", "Ikki daryo oralig'ini", "Cho'l hududlarni", "Dengiz sohilini"],
    correctAnswer: "Ikki daryo oralig'ini",
    difficulty: "hard",
    timeLimit: 40,
  },

  // --- Geografiya va Astronomiya ---
  {
    id: "12",
    subject: "Geografiya",
    question: "Dunyodagi eng chuqur ko'l qaysi va u qayerda joylashgan?",
    options: ["Kaspiy (O'rta Osiyo)", "Baykal (Rossiya)", "Tityaka (Janubiy Amerika)", "Superior (AQSh)"],
    correctAnswer: "Baykal (Rossiya)",
    difficulty: "hard",
    timeLimit: 40,
  },
  {
    id: "13",
    subject: "Astronomiya",
    question: "Quyosh sistemasida o'z o'qi atrofida teskari yo'nalishda (sharqdan g'arbga) aylanuvchi sayyora qaysi?",
    options: ["Mars", "Venera (Zuhra)", "Yupiter", "Saturn"],
    correctAnswer: "Venera (Zuhra)",
    difficulty: "hard",
    timeLimit: 45,
  },
  {
    id: "14",
    subject: "Geografiya",
    question: "Yer yuzidagi eng yirik tropik o'rmonlar (Amazoniya) asosan qaysi qit'ada joylashgan?",
    options: ["Afrika", "Janubiy Amerika", "Avstraliya", "Osiyo"],
    correctAnswer: "Janubiy Amerika",
    difficulty: "medium",
    timeLimit: 35,
  },

  // --- Biologiya va Anatomiya ---
  {
    id: "15",
    subject: "Biologiya",
    question: "Hujayraning energetik markazi, ya'ni ATF (adenozintrifosfat) sintez qiluvchi organella qaysi?",
    options: ["Ribosoma", "Mitoxondriya", "Xloroplast", "Golji majmuasi"],
    correctAnswer: "Mitoxondriya",
    difficulty: "hard",
    timeLimit: 40,
  },
  {
    id: "16",
    subject: "Biologiya",
    question: "DNK molekulasining asosiy tuzilish shakli qanday?",
    options: ["To'g'ri zanjirli", "Ikki karrali spiral (spiralsimon)", "Halqasimon tarqoq", "Uchburchak panjara"],
    correctAnswer: "Ikki karrali spiral (spiralsimon)",
    difficulty: "medium",
    timeLimit: 35,
  },

  // --- Informatika va Dasturlash ---
  {
    id: "17",
    subject: "Informatika",
    question: "Ikkilik sanoq tizimidagi 1010 soni o'nlik sanoq sistemasida nechiga teng?",
    options: ["8", "10", "12", "14"],
    correctAnswer: "10",
    difficulty: "hard",
    timeLimit: 40,
  },
  {
    id: "18",
    subject: "Informatika",
    question: "Dasturlashda ma'lumotlar bazasidan so'rovlar yuborish uchun eng ko'p ishlatiladigan til qaysi?",
    options: ["HTML", "SQL", "CSS", "JSON"],
    correctAnswer: "SQL",
    difficulty: "medium",
    timeLimit: 35,
  },
  {
    id: "19",
    subject: "Informatika",
    question: "Qaysi xotira turi kompyuter o'chirilganda ma'lumotlarni saqlab qolmaydi (energoresursga bog'liq)?",
    options: ["ROM", "SSD", "RAM", "HDD"],
    correctAnswer: "RAM",
    difficulty: "medium",
    timeLimit: 35,
  },

  // --- Adabiyot va Til ---
  {
    id: "20",
    subject: "Adabiyot",
    question: "Alisher Navoiyning mashhur 'Xamsa' dostonlari nechta dostonni o'z ichiga oladi?",
    options: ["3 ta", "4 ta", "5 ta", "7 ta"],
    correctAnswer: "5 ta",
    difficulty: "medium",
    timeLimit: 30,
  },
  {
    id: "21",
    subject: "Ingliz tili",
    question: "Qaysi variant Third Conditional (Uchinchi shartli gap) tuzilishiga to'g'ri keladi?",
    options: [
      "If I go, I will see him.",
      "If I went, I would see him.",
      "If I had gone, I would have seen him.",
      "If I go, I saw him."
    ],
    correctAnswer: "If I had gone, I would have seen him.",
    difficulty: "hard",
    timeLimit: 45,
  }
];