export const comments = [
  {
    id: 1,
    fullName: "Dilnoza Karimova",
    role: "Boshlang'ich sinf o'qituvchisi",
    school: "31-maktab, Toshkent",
    rating: 5,
    comment: "Baamboozle o'yini darslarimni butunlay o'zgartirib yubordi. Bolalar endi darsni intiqlik bilan kutishadi. Matematika darslarida o'yin orqali misollar yechish ularga juda yoqadi. 2-haftada o'zlashtirish 30% ga oshdi!",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Dilnoza",
    likes: 234,
    timeAgo: "2 kun oldin",
    game: "Baamboozle",
    color: "from-[#f7c66d] to-[#e48b52]",
    bgColor: "bg-[#fff8e7]"
  },
  {
    id: 2,
    fullName: "Madina Rahimova",
    role: "Ingliz tili o'qituvchisi",
    school: "15-IDUM, Samarqand",
    rating: 5,
    comment: "Treasure Hunt - bu ajoyib! O'quvchilarim ingliz tilida so'zlashishdan qo'rqmasdan, o'yin orqali o'rganishmoqda. Har bir darsimiz sarguzashtga aylangan.",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Madina",
    likes: 189,
    timeAgo: "5 kun oldin",
    game: "Treasure Hunt",
    color: "from-[#e7b16d] to-[#c67a59]",
    bgColor: "bg-[#fff3e8]"
  },
  {
    id: 3,
    fullName: "Ozodbek Salimov",
    role: "TDIU 3-kurs talabasi",
    school: "TDIU, Toshkent",
    rating: 5,
    comment: "Keyingi yil praktikada shu platformadan foydalanaman. Raxmat <3",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Shahzod",
    likes: 42,
    timeAgo: "1 hafta oldin",
    game: "All game",
    color: "from-[#e58ca0] to-[#bc5c74]",
    bgColor: "bg-[#fff0f3]"
  },
  {
    id: 4,
    fullName: "Gulnora Azizova",
    role: "Fizika o'qituvchisi",
    school: "12-maktab, Andijon",
    rating: 5,
    comment: "Fizika formulalari endi bolalar uchun o'yin. Platformadagi barcha o'yinlarni sinab ko'rdik, eng sevimlisi Baamboozle.",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Gulnora",
    likes: 203,
    timeAgo: "3 kun oldin",
    game: "Baamboozle",
    color: "from-[#f7c66d] to-[#e48b52]",
    bgColor: "bg-[#fff8e7]"
  },
  {
    id: 5,
    fullName: "Rustam Sobirov",
    role: "Direktor",
    school: "23-maktab, Namangan",
    rating: 5,
    comment: "Butun maktabimizda ushbu platformani joriy qildik. O'qituvchilar darsga tayyorgarlik ko'rishda vaqtni tejashyapti, o'quvchilar esa darsga qiziqish bilan qatnashishyapti.",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Rustam",
    likes: 312,
    timeAgo: "1 hafta oldin",
    game: "Platforma",
    color: "from-[#e07c8e] to-[#a66466]",
    bgColor: "bg-[#fff1f0]"
  },
  {
    id: 6,
    fullName: "Nilufar Karimova",
    role: "Ona tili o'qituvchisi",
    school: "8-maktab, Farg'ona",
    rating: 5,
    comment: "Grammatika qoidalarini o'rgatish eng qiyin vazifa edi. Treasure Hunt orqali bolalar gap bo'laklarini o'yin orqali o'rganishdi.",
    avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Nilufar",
    likes: 178,
    timeAgo: "4 kun oldin",
    game: "Treasure Hunt",
    color: "from-[#e7b16d] to-[#c67a59]",
    bgColor: "bg-[#fff3e8]"
  },
  {
        id: 7,
        fullName: "Zulfiya Karimova",
        role: "Boshlang'ich sinf o'qituvchisi",
        school: "67-umumiy o'rta maktab, Toshkent",
        avatar: "https://api.dicebear.com/9.x/avataaars/svg?seed=Nilufar",
        rating: 5,
        game: "Matematik Poyga",
        comment: "Dastur bolalarning mantiqiy fikrlashini ajoyib rivojlantiradi. Har bir dars interaktiv va qiziqarli, o'quvchilar zavq bilan qatnashadi.",
        likes: 124,
        timeAgo: "2 kun oldin",
        bgColor: "bg-gradient-to-br from-rose-50/60 to-orange-50/40",
        color: "from-rose-400 to-orange-400"
      }
];