export const comments = [
  {
    id: 1,
    fullName: "Dilnoza Karimova",
    role: "Boshlang'ich sinf o'qituvchisi",
    school: "31-maktab, Toshkent",
    rating: 5,
    comment:
      "Baamboozle o'yini darslarimni butunlay o'zgartirib yubordi. Bolalar endi darsni intiqlik bilan kutishadi. Matematika darslarida o'yin orqali misollar yechish ularga juda yoqadi. 2-haftada o'zlashtirish 30% ga oshdi!",
    avatar: "https://i.pravatar.cc/150?img=5",
    likes: 234,
    timeAgo: "2 kun oldin",
    game: "Baamboozle",
    color: "from-[#f7c66d] to-[#e48b52]",
    bgColor: "bg-[#fff8e7]",
  },
  {
    id: 2,
    fullName: "Madina Rahimova",
    role: "Ingliz tili o'qituvchisi",
    school: "15-IDUM, Samarqand",
    rating: 5,
    comment:
      "Treasure Hunt - bu ajoyib! O'quvchilarim ingliz tilida so'zlashishdan qo'rqmasdan, o'yin orqali o'rganishmoqda. Har bir darsimiz sarguzashtga aylangan.",
    avatar: "https://i.pravatar.cc/150?img=9",
    likes: 189,
    timeAgo: "5 kun oldin",
    game: "Treasure Hunt",
    color: "from-[#e7b16d] to-[#c67a59]",
    bgColor: "bg-[#fff3e8]",
  },
  {
    id: 3,
    fullName: "Ozodbek Salimov",
    role: "TDIU 3-kurs talabasi",
    school: "TDIU, Toshkent",
    rating: 5,
    comment: "Keyingi yil praktikada shu platformadan foydalanaman. Raxmat <3",
    avatar: "https://i.pravatar.cc/150?img=12",
    likes: 426,
    timeAgo: "1 hafta oldin",
    game: "All game",
    color: "from-[#e58ca0] to-[#bc5c74]",
    bgColor: "bg-[#fff0f3]",
  },
  {
    id: 4,
    fullName: "Gulnora Azizova",
    role: "Fizika o'qituvchisi",
    school: "12-maktab, Andijon",
    rating: 5,
    comment:
      "Fizika formulalari endi bolalar uchun o'yin. Platformadagi barcha o'yinlarni sinab ko'rdik, eng sevimlisi Baamboozle.",
    avatar: "https://i.pravatar.cc/150?img=20",
    likes: 203,
    timeAgo: "3 kun oldin",
    game: "Baamboozle",
    color: "from-[#f7c66d] to-[#e48b52]",
    bgColor: "bg-[#fff8e7]",
  },
  {
    id: 5,
    fullName: "Rustam Sobirov",
    role: "Direktor",
    school: "23-maktab, Namangan",
    rating: 5,
    comment:
      "Butun maktabimizda ushbu platformani joriy qildik. O'qituvchilar darsga tayyorgarlik ko'rishda vaqtni tejashyapti, o'quvchilar esa darsga qiziqish bilan qatnashishyapti.",
    avatar: "https://i.pravatar.cc/150?img=14",
    likes: 312,
    timeAgo: "1 hafta oldin",
    game: "Platforma",
    color: "from-[#e07c8e] to-[#a66466]",
    bgColor: "bg-[#fff1f0]",
  },
  {
    id: 6,
    fullName: "Nilufar Karimova",
    role: "Ona tili o'qituvchisi",
    school: "8-maktab, Farg'ona",
    rating: 5,
    comment:
      "Grammatika qoidalarini o'rgatish eng qiyin vazifa edi. Treasure Hunt orqali bolalar gap bo'laklarini o'yin orqali o'rganishdi.",
    avatar: "https://i.pravatar.cc/150?img=23",
    likes: 178,
    timeAgo: "4 kun oldin",
    game: "Treasure Hunt",
    color: "from-[#e7b16d] to-[#c67a59]",
    bgColor: "bg-[#fff3e8]",
  },
  {
    id: 7,
    fullName: "Zulfiya Karimova",
    role: "Boshlang'ich sinf o'qituvchisi",
    school: "67-umumiy o'rta maktab, Toshkent",
    avatar: "https://i.pravatar.cc/150?img=28",
    rating: 5,
    game: "Matematik Poyga",
    comment:
      "Dastur bolalarning mantiqiy fikrlashini ajoyib rivojlantiradi. Har bir dars interaktiv va qiziqarli, o'quvchilar zavq bilan qatnashadi.",
    likes: 124,
    timeAgo: "2 kun oldin",
    bgColor: "bg-gradient-to-br from-rose-50/60 to-orange-50/40",
    color: "from-rose-400 to-orange-400",
  },
  {
    id: 8,
    fullName: "Shahzod Nurmatov",
    role: "Matematika o'qituvchisi",
    school: "45-maktab, Buxoro",
    rating: 5,
    comment:
      "Matematik Poyga orqali o'quvchilar tez va aniq hisoblashni o'rganishyapti. Darslar juda jonlandi.",
    avatar: "https://i.pravatar.cc/150?img=33",
    likes: 156,
    timeAgo: "1 kun oldin",
    game: "Matematik Poyga",
    color: "from-rose-400 to-orange-400",
    bgColor: "bg-orange-50",
  },
  {
    id: 9,
    fullName: "Aziza Tursunova",
    role: "Ingliz tili o'qituvchisi",
    school: "10-maktab, Qarshi",
    rating: 5,
    comment:
      "Treasure Hunt orqali speaking skill juda tez rivojlandi. O'quvchilarim endi faol gapirishyapti!",
    avatar: "https://i.pravatar.cc/150?img=32",
    likes: 210,
    timeAgo: "3 kun oldin",
    game: "Treasure Hunt",
    color: "from-[#e7b16d] to-[#c67a59]",
    bgColor: "bg-[#fff3e8]",
  },
  {
    id: 10,
    fullName: "Jasur Qodirov",
    role: "IT o'qituvchisi",
    school: "IT Park School, Toshkent",
    rating: 5,
    comment:
      "Platforma UX jihatdan juda qulay. O'quvchilar ham tez tushunib ketishyapti.",
    avatar: "https://i.pravatar.cc/150?img=52",
    likes: 98,
    timeAgo: "2 kun oldin",
    game: "Platforma",
    color: "from-[#e07c8e] to-[#a66466]",
    bgColor: "bg-[#fff1f0]",
  },
  {
    id: 11,
    fullName: "Malika Ergasheva",
    role: "Boshlang'ich sinf o'qituvchisi",
    school: "5-maktab, Urganch",
    rating: 5,
    comment:
      "Bolalar darsdan chiqishni xohlamayapti! Eng yaxshi feedback shu bo'lsa kerak 😊",
    avatar: "https://i.pravatar.cc/150?img=47",
    likes: 175,
    timeAgo: "4 kun oldin",
    game: "Baamboozle",
    color: "from-[#f7c66d] to-[#e48b52]",
    bgColor: "bg-[#fff8e7]",
  },
  {
    id: 12,
    fullName: "Bekzod Aliyev",
    role: "Talaba",
    school: "SamDU, Samarqand",
    rating: 5,
    comment:
      "Kelajakda o'qituvchi bo'lsam, albatta shu platformani ishlataman!",
    avatar: "https://i.pravatar.cc/150?img=54",
    likes: 67,
    timeAgo: "6 kun oldin",
    game: "All game",
    color: "from-[#e58ca0] to-[#bc5c74]",
    bgColor: "bg-[#fff0f3]",
  },
  {
    id: 13,
    fullName: "Dilshoda Xasanova",
    role: "Ona tili o'qituvchisi",
    school: "14-maktab, Namangan",
    rating: 5,
    comment:
      "Grammatika osonlashdi! O'quvchilar qoidalarni tez eslab qolishyapti.",
    avatar: "https://i.pravatar.cc/150?img=41",
    likes: 132,
    timeAgo: "2 kun oldin",
    game: "Treasure Hunt",
    color: "from-[#e7b16d] to-[#c67a59]",
    bgColor: "bg-[#fff3e8]",
  },
  {
    id: 14,
    fullName: "Umidjon Rahmatov",
    role: "Direktor o'rinbosari",
    school: "9-maktab, Jizzax",
    rating: 5,
    comment:
      "O'qituvchilar uchun ham juda katta yordam. Tayyor kontentlar juda sifatli.",
    avatar: "https://i.pravatar.cc/150?img=59",
    likes: 201,
    timeAgo: "5 kun oldin",
    game: "Platforma",
    color: "from-[#e07c8e] to-[#a66466]",
    bgColor: "bg-[#fff1f0]",
  },
  {
    id: 15,
    fullName: "Zafarbek Yo'ldoshev",
    role: "Fizika o'qituvchisi",
    school: "21-maktab, Termiz",
    rating: 5,
    comment:
      "Murakkab mavzularni ham o'yin orqali tushuntirish mumkinligini ko'rdim.",
    avatar: "https://i.pravatar.cc/150?img=65",
    likes: 145,
    timeAgo: "3 kun oldin",
    game: "Baamboozle",
    color: "from-[#f7c66d] to-[#e48b52]",
    bgColor: "bg-[#fff8e7]",
  },
  {
    id: 16,
    fullName: "Gulbahor Toshpulatova",
    role: "Boshlang'ich sinf o'qituvchisi",
    school: "3-maktab, Nukus",
    rating: 5,
    comment: "Bolalar har safar yangi o'yin kutishyapti. Juda zo'r platforma!",
    avatar: "https://i.pravatar.cc/150?img=44",
    likes: 188,
    timeAgo: "1 kun oldin",
    game: "Matematik Poyga",
    color: "from-rose-400 to-orange-400",
    bgColor: "bg-orange-50",
  },
  {
    id: 17,
    fullName: "Sardor Eshonqulov",
    role: "IT mutaxassis",
    school: "Freelancer",
    rating: 5,
    comment: "Frontend juda chiroyli qilingan 👏 UX ham mukammal.",
    avatar: "https://i.pravatar.cc/150?img=68",
    likes: 90,
    timeAgo: "1 hafta oldin",
    game: "Platforma",
    color: "from-[#e07c8e] to-[#a66466]",
    bgColor: "bg-[#fff1f0]",
  },
];
